import type { ShaderStyle } from "./index";

/**
 * Per-style uniform values, copied from pokebox's `DEFAULT_CONFIG.shaders`
 * (src/data/defaults.ts) via its uniform registry (src/data/shaderRegistry.ts).
 * Keys are the GLSL uniform names. Not tuned: these are the values pokebox ships.
 */
export const SHADER_PRESETS: Record<ShaderStyle, Record<string, number>> = {
  "flatsilver-reverse": {
    uRainbowScale: 0.6,
    uRainbowShift: 0.9,
    uRainbowSaturation: 0.5,
    uRainbowOpacity: 0.75,
    uSpotlightRadius: 1.05,
    uSpotlightIntensity: 2.55,
    uGrainScale: 1.2,
    uGrainIntensity: 1.0,
    uBaseBrightness: 0.6,
    uBaseContrast: 0.9,
    uBaseSaturation: 3.0,
  },
  "ultra-rare": {
    uBaseBrightness: 1.6,
    uShineBrightness: 0.22,
    uShineContrast: 1.0,
    uShineSaturation: 20.0,
    uShineAfterBrightness: 0.2,
    uShineAfterContrast: 0.15,
    uShineAfterSaturation: 1.0,
    uShineBaseBrightness: 1.2,
    uShineBaseContrast: 1.65,
    uShineBaseSaturation: 3.3,
    uGlareContrast: 0.8,
    uGlare2Contrast: 0.45,
    uRotateDelta: 99.0,
    uAngle1Mult: 0.65,
    uAngle2Mult: 0.65,
    uBgYMult1: 0.45,
    uBgYMult2: 1.2,
    uBarAngle: 128.5,
    uBarOffsetBgXMult: 0.9,
    uBarOffsetBgYMult: 1.1,
    uBarFrequency: 2.5,
    uBarIntensityStart1: 0.18,
    uBarIntensityEnd1: 0.51,
    uBarIntensityStart2: 0.18,
    uBarIntensityEnd2: 0.8,
    uSparkleIntensity: 0.35,
    uSparkleRadius: 1.0,
    uSparkleContrast: 2.4,
    uSparkleColorShift: 5.0,
  },
  "illustration-rare": {
    uRainbowScale: 0.5,
    uBarAngle: 132.0,
    uBarDensity: 2.6,
    uBarDensity2: 1.8,
    uBarOffsetBgYMult: -0.7,
    uBar2OffsetBgYMult: 0.85,
    uBarWidth: 5.4,
    uBarWidth2: 3.95,
    uBarIntensity: 20.0,
    uBarIntensity2: 10.35,
    uBarHue: 231.0,
    uBarMediumSaturation: 0.33,
    uBarMediumLightness: 0.6,
    uBarBrightSaturation: 0.38,
    uBarBrightLightness: 0.71,
    uBarHue2: 248.0,
    uBarMediumSaturation2: 0.17,
    uBarMediumLightness2: 0.43,
    uBarBrightSaturation2: 0.19,
    uBarBrightLightness2: 0.83,
    uShine1Contrast: 1.5,
    uShine1Saturation: 0.8,
    uShine2Opacity: 0.85,
    uGlareOpacity: 0.9,
  },
  // double-rare has no configurable uniforms in pokebox.
  "double-rare": {},
};
